#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${PROJECT_DIR}/../.." && pwd)"

EXAMPLE_FILE="${PROJECT_DIR}/terraform.tfvars.example"
OUTPUT_FILE="${PROJECT_DIR}/terraform.tfvars"
SAMPLE_DIR="${REPO_ROOT}/samples/pgtap-incus-lab"
SAMPLE_CONFIG="${SAMPLE_DIR}/config.env"

echo "[INFO] PostgreSQL Lab用 terraform.tfvarsを作成します。"

if [[ ! -f "${EXAMPLE_FILE}" ]]; then
  echo "[ERROR] サンプルファイルが見つかりません。"
  exit 1
fi

if [[ -f "${OUTPUT_FILE}" ]]; then
  echo "[ERROR] terraform.tfvarsはすでに存在します。"
  echo "[INFO] 既存設定を上書きしないため、処理を終了します。"
  exit 1
fi

echo
echo "[INFO] 利用可能なネットワークインターフェース:"
ip -br address
echo

read -r -p "有線LANインターフェース名 [eno1]: " LAN_INTERFACE
LAN_INTERFACE="${LAN_INTERFACE:-eno1}"

if [[ ! -d "/sys/class/net/${LAN_INTERFACE}" ]]; then
  echo "[ERROR] ネットワークインターフェースが存在しません: ${LAN_INTERFACE}"
  exit 1
fi

echo
read -r -p "IPv4設定方式 [dhcp/static] [dhcp]: " NETWORK_MODE
NETWORK_MODE="${NETWORK_MODE:-dhcp}"

if [[ "${NETWORK_MODE}" != "dhcp" && "${NETWORK_MODE}" != "static" ]]; then
  echo "[ERROR] dhcpまたはstaticを指定してください。"
  exit 1
fi

GUEST_IPV4_ADDRESS=""
GUEST_IPV4_PREFIX="24"

if [[ "${NETWORK_MODE}" == "static" ]]; then
  read -r -p "コンテナのLAN側固定IPv4アドレス: " GUEST_IPV4_ADDRESS

  if [[ -z "${GUEST_IPV4_ADDRESS}" ]]; then
    echo "[ERROR] 固定IPv4アドレスは必須です。"
    exit 1
  fi

  read -r -p "IPv4プレフィックス長 [24]: " GUEST_IPV4_PREFIX
  GUEST_IPV4_PREFIX="${GUEST_IPV4_PREFIX:-24}"
fi

echo
read -r -s -p "PostgreSQL管理者 postgres のパスワード: " POSTGRES_PASSWORD
echo

if [[ -z "${POSTGRES_PASSWORD}" ]]; then
  echo "[ERROR] パスワードを入力してください。"
  exit 1
fi

cp "${EXAMPLE_FILE}" "${OUTPUT_FILE}"

sed -i \
  -e "s|^lan_interface[[:space:]]*=.*|lan_interface = \"${LAN_INTERFACE}\"|" \
  -e "s|^network_mode[[:space:]]*=.*|network_mode = \"${NETWORK_MODE}\"|" \
  -e "s|^guest_ipv4_address[[:space:]]*=.*|guest_ipv4_address = \"${GUEST_IPV4_ADDRESS}\"|" \
  -e "s|^guest_ipv4_prefix[[:space:]]*=.*|guest_ipv4_prefix = ${GUEST_IPV4_PREFIX}|" \
  -e "s|^postgres_password[[:space:]]*=.*|postgres_password = \"${POSTGRES_PASSWORD}\"|" \
  "${OUTPUT_FILE}"

chmod 600 "${OUTPUT_FILE}"

echo
echo "[INFO] terraform.tfvarsを作成しました。"
echo "[INFO] 出力先: ${OUTPUT_FILE}"

if [[ "${NETWORK_MODE}" == "static" ]]; then
  mkdir -p "${SAMPLE_DIR}"

  cat > "${SAMPLE_CONFIG}" <<EOF
# Auto-generated by infra/incus-postgresql/scripts/create-terraform-tfvars.sh
DB_HOST=${GUEST_IPV4_ADDRESS}
DB_PORT=5432
DB_USER=postgres
EOF

  chmod 600 "${SAMPLE_CONFIG}"

  echo "[INFO] pgTAP Lab用 config.env を作成しました。"
  echo "[INFO] 出力先: ${SAMPLE_CONFIG}"
else
  echo "[INFO] DHCPを選択したため、samples/pgtap-lab/config.env は作成しません。"
  echo "[INFO] IP確定後にconfig.envへDB_HOSTを設定してください。"
fi

echo
echo "[INFO] PostgreSQL管理ユーザー: postgres"
echo "[INFO] 初期作成DB: PostgreSQL標準のpostgres DBのみ"
echo "[INFO] pg_hba.conf: host all postgres 0.0.0.0/0 trust をCloud-init側で設定します。"
